language: java
addons:
  sonarcloud:
    organization: "sherry975-rxi"
    token:
      secure: sherry975 # encrypted value of your token

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=sherry975-rxi_projectmanagerapplication
