language: java
addons:
  sonarcloud:
    organization: "sherry975-rxi"
    token:
      secure: 1b268adb719bbb67aa60a30231d47f3e4c3c76bf # encrypted value of your token

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=sherry975-rxi_projectmanagerapplication
