# Create image from openjdk image (https://hub.docker.com/_/openjdk/)
FROM openjdk:8

# Get jar file into the container
ADD /release.jar release.jar

# prepare image to start application when running image
ENTRYPOINT java -jar release.jar