node {

    // define names for the release images
    def DEPENDENCIES_IMAGE_NAME = '1171476/project-dependencies:latest'
    //def dependenciesImage

    def RELEASE_BACKEND_IMAGE_NAME = '1171473/switch-2017-g003-pm-backend' 
    def releaseBackendImage

    def RELEASE_FRONTEND_IMAGE_NAME = '1171473/switch-2017-g003-pm-frontend' 
    def releaseFrontendImage

    stage('Clone repository') {

        checkout scm
    }


    docker.image("1171476/project-dependencies:latest").inside(){

        stage('Unit Tests') {
            sh 'mvn test'
        }  

         stage('Integration Tests') {
            
            sh 'mvn failsafe:integration-test'
        }  
    }
    
    stage('Create project backend image') {
            
        releaseBackendImage = docker.build("$RELEASE_BACKEND_IMAGE_NAME", "-f PipelineMYSQL/backend/Dockerfile .")

    }

    stage('Create project frontend image') {
            
        releaseFrontendImage = docker.build("$RELEASE_FRONTEND_IMAGE_NAME", "-f PipelineMYSQL/frontend/Dockerfile .")

    }

    stage('Publish images in DockerHub') {
        withCredentials([usernamePassword(credentialsId: 'group003-docker-hub', usernameVariable: 'DockerHubUsername', passwordVariable: 'DockerHubPassword')]) {
            sh """
                echo $DockerHubPassword | docker login -u $DockerHubUsername --password-stdin
                docker tag ${releaseBackendImage.id} 1171473/switch-2017-g003-pm-backend:version-${env.BUILD_NUMBER}
                docker push $RELEASE_BACKEND_IMAGE_NAME
                docker tag ${releaseFrontendImage.id} 1171473/switch-2017-g003-pm-frontend:version-${env.BUILD_NUMBER}
                docker push $RELEASE_FRONTEND_IMAGE_NAME
            """                 
            } 
    }

        stage('Clean Up') {
        
            sh """
                docker images | grep "1171473" | awk -F ' ' '{print $3}' | xargs docker rmi -f
            """                 
             
    } 

}