package project.model;

import java.util.Random;

public class CodeGenerator {

    private String generatedCode;


    public String generateCode() {

        Random rand = new Random();
        Integer randomNumber = 100000 + rand.nextInt(900000);
        this.generatedCode = randomNumber.toString();


        return generatedCode;
    }


    /**
     * Checks if the code generated by the Administrator upon user's registry matches the code
     * typed by the user
     * @param codeToCheck Code to be checked for match
     * @return TRUE if it matches, FALSE if it doesn't
     */
    public Boolean doesCodeGeneratedMatch (String codeToCheck){

        return codeToCheck.equals(this.generatedCode);

    }

}
