// SIGNUP
export const INCREASE_SIGN_UP_STEP = 'INCREASE_SIGN_UP_STEP';

// PROJECTS
export const GET_USER_PROJECTS_FULLFIELD = 'GET_USER_PROJECTS_FULLFIELD';
export const GET_ACTIVE_PROJECTS_FULLFIELD = 'GET_ACTIVE_PROJECTS_FULLFIELD';
export const PROJECT_TABLE_DETAILS_TOOGLE = 'PROJECT_TABLE_DETAILS_TOOGLE';

// TASKS
export const GET_AVAILABLE_COLLABORATORS_FOR_TASK_ERROR =
    'GET_AVAILABLE_COLLABORATORS_FOR_TASK_ERROR';
export const GET_AVAILABLE_COLLABORATORS_FOR_TASK_FULLFIELD =
    'GET_AVAILABLE_COLLABORATORS_FOR_TASK_FULLFIELD';
export const CHANGE_TASK_FILTER = 'CHANGE_TASK_FILTER';
export const ALL_PROJECT_TASKS_FETCHED = 'ALL_PROJECT_TASKS_FETCHED';
